### GET ALL PETS
GET http://localhost:3000/api/pets
Accept: application/json

### CREATE NEW PET
POST http://localhost:3000/api/pets
Accept: application/json
Content-Type: application/json

{
  "name": "",
  "species": "",
  "price":
}

### GET PETS BY ITS ID
GET http://localhost:3000/api/pets/7
Accept: application/json
Content-Type: application/json

### UPDATE PETS BY ITS ID
PUT http://localhost:3000/api/pets/8
Accept: application/json
Content-Type: application/json

{
  "name": "",
  "species": "",
  "price": 
}

### DELETE PETS BY ITS ID
DELETE http://localhost:3000/api/pets/7